In [4]:
import pandas as pd
import numpy as np

l = ["11", "12", "13", "14", "15", "16"]

l_files = []
for i in range (0,len(l)):
    l_files.append("C:/Users/jwolf/Google Drive/00_Getin/04_Programação/Originais/Nados_Vivos/\
nascimentos {0} idade da mãe sexo concelho.csv".format(l[i]))
    
x=0
for i in l_files: 
    urso(i).to_csv("C:/Users/jwolf/Google Drive/00_Getin/04_Programação/Novos/Nasc_idade_m{0}.csv".format(l[x]),\
                   sep=';', encoding='ANSI', index=True, header=True)
    x+=1
    print (i)

C:/Users/jwolf/Google Drive/00_Getin/04_Programação/Originais/Nados_Vivos/nascimentos 11 idade da mãe sexo concelho.csv
C:/Users/jwolf/Google Drive/00_Getin/04_Programação/Originais/Nados_Vivos/nascimentos 12 idade da mãe sexo concelho.csv
C:/Users/jwolf/Google Drive/00_Getin/04_Programação/Originais/Nados_Vivos/nascimentos 13 idade da mãe sexo concelho.csv
C:/Users/jwolf/Google Drive/00_Getin/04_Programação/Originais/Nados_Vivos/nascimentos 14 idade da mãe sexo concelho.csv
C:/Users/jwolf/Google Drive/00_Getin/04_Programação/Originais/Nados_Vivos/nascimentos 15 idade da mãe sexo concelho.csv
C:/Users/jwolf/Google Drive/00_Getin/04_Programação/Originais/Nados_Vivos/nascimentos 16 idade da mãe sexo concelho.csv

In [3]:
def urso(nome_arquivo):

    df = pd.read_csv(nome_arquivo,encoding="ANSI", engine='python', sep = ";", header = 0, dtype= {'Code': str})
    df['code'], df['nome'] = df.iloc[:,1].str.split(':').str
    df.drop([0,2,4,5,6], inplace = True)
    cols = [1,96]
    df.drop(df.columns[cols], inplace = True, axis = 1)
    l =['ano']
    for i in range (0,len(df.columns)-3): 
            if i < (len(df.columns)-3)/2:
                l.append("H_")
            else: 
                l.append("M_")
    l.append("")
    l.append("nome")
    df.loc[1] = l


    df.index = df ['code']
    df.drop(['code'], inplace = True,axis=1)
    df
    lista =['ano']
    for i in range (1,len(df.columns)-1): 
            lista.append(str(df.iloc[0,i]) + str(df.iloc[1,i]))
    lista.append('nome')
    df.columns = lista
    df.drop(df.index[[0,1]], inplace = True)

    anos2 = df.ano.unique()
    anos2 = np.delete (anos2,1)

    for i in range(int(len(df.index))):
        df.iloc[i,0] = anos2[0]

    cols = df.columns.tolist()
    cols = cols[-1:] + cols[:-1]
    df = df[cols]


    l_index = []

    for i in df.index:
        if len(i) > 4: 
            l_index.append(i[3:])
        else: 
            l_index.append(i)

    df.index = l_index

    df

    cols1 = cols[2:(int(len(cols[2:])/2+2))]

    df_h = df[cols1]
    df_h = df_h.apply(pd.to_numeric)
    df_h

    cols2 = cols[(int(len(cols[2:])/2+2)):]
    df_m = df[cols2]
    df_m = df_m.apply(pd.to_numeric)

    df_m.columns = df_h.columns 

    df_add = df_m.add(df_h, fill_value=0)
    df_add['ano'] = df ['ano']

    df_soma = pd.DataFrame()
    k=0
    for i in range (0,(len(df_add.columns)//5)):
        df_soma[i] = df_add.iloc[:, k:k+5].sum(axis = 1)
        k+=5
    df_soma[i+1] = df_add.loc[:,'H_55 e mais anos']
    df_soma['ano'] = df_add.loc[:,'ano']
    l = ('10_14', '15_19', '20_24', '25_29', '30_34','35_39', '40_44', '45_49', '50_54', '55_59', 'ano')
    df_soma.columns = l 

    l_mun = []
    for i in df_soma.index:
        if len(i) == 4: 
            l_mun.append(i)

    myset = set(l_mun)
    l_mun = list(myset)
    df_soma = df_soma.loc[myset]
    df_soma.index.name = 'code'
    df_soma
    return (df_soma)

In [9]:
import pandas as pd
import numpy as np

nome_arquivo = "C:/Users/jwolf/Google Drive/00_Getin/04_Programação/Originais/Nados_Vivos/\
nascimentos 11 idade da mãe sexo concelho.csv"


df = pd.read_csv(nome_arquivo,encoding="ANSI", engine='python', sep = ";", header = 0, dtype= {'Code': str})
df['code'], df['nome'] = df.iloc[:,1].str.split(':').str
df.drop([0,2,4,5,6], inplace = True)
cols = [1,96]
df.drop(df.columns[cols], inplace = True, axis = 1)
l =['ano']
for i in range (0,len(df.columns)-3): 
        if i < (len(df.columns)-3)/2:
            l.append("H_")
        else: 
            l.append("M_")
l.append("")
l.append("nome")
df.loc[1] = l


df.index = df ['code']
df.drop(['code'], inplace = True,axis=1)
df
lista =['ano']
for i in range (1,len(df.columns)-1): 
        lista.append(str(df.iloc[0,i]) + str(df.iloc[1,i]))
lista.append('nome')
df.columns = lista
df.drop(df.index[[0,1]], inplace = True)
df
anos2 = df.ano.unique()
anos2 = np.delete (anos2,1)

for i in range(int(len(df.index))):
    df.iloc[i,0] = anos2[0]

cols = df.columns.tolist()
cols = cols[-1:] + cols[:-1]
df = df[cols]

df
l_index = []

for i in df.index:
    if len(i) > 4: 
        l_index.append(i[3:])
    else: 
        l_index.append(i)
l_index
df.index = l_index



cols1 = cols[2:(int(len(cols[2:])/2+2))]

df_h = df[cols1]
df_h = df_h.apply(pd.to_numeric)
df_h

cols2 = cols[(int(len(cols[2:])/2+2)):]
df_m = df[cols2]
df_m = df_m.apply(pd.to_numeric)

df_m.columns = df_h.columns 

df_add = df_m.add(df_h, fill_value=0)

# cols = df_add.columns.tolist()
# cols =  cols[1:] + cols[:1]
# df_add = df_add[cols]
df_add['ano'] = df ['ano']
df_add
df_soma = pd.DataFrame()
k=0
for i in range (0,(len(df_add.columns)//5)):
    df_soma[i] = df_add.iloc[:, k:k+5].sum(axis = 1)
    k+=5
df_soma[i+1] = df_add.loc[:,'H_55 e mais anos']
df_soma['ano'] = df_add.loc[:,'ano']
l = ('10_14', '15_19', '20_24', '25_29', '30_34','35_39', '40_44', '45_49', '50_54', '55_59', 'ano')
df_soma.columns = l 

l_mun = []
for i in df_soma.index:
    if len(i) == 4: 
        l_mun.append(i)

myset = set(l_mun)
l_mun = list(myset)
df_soma = df_soma.loc[myset]
df_soma.index.name = 'code'
df_soma

,10_14,15_19,20_24,25_29,30_34,35_39,40_44,45_49,50_54,55_59,ano
code,,,,,,,,,,,
0617,1,1,8,20,27,9,1,0,0,0,2011
1403,0,6,30,62,80,40,7,0,0,0,2011
1316,0,33,87,231,274,172,31,1,0,0,2011
1816,0,3,14,24,45,23,1,0,0,0,2011
0214,0,6,8,16,16,5,2,0,0,0,2011
0601,0,2,10,29,27,3,1,0,0,0,2011
4202,0,3,6,12,15,5,1,0,0,0,2011
0117,0,2,10,17,31,14,0,0,0,0,2011
1010,0,11,29,73,122,75,18,0,0,0,2011
0911,0,1,7,16,13,9,3,0,0,0,2011
1502,0,4,14,43,91,57,8,0,0,0,2011
1513,0,10,23,45,47,29,5,0,0,0,2011
1008,0,2,2,3,5,5,2,0,0,0,2011
0309,0,2,18,54,58,35,4,0,0,0,2011
1704,0,1,4,8,19,3,0,0,0,0,2011
0209,0,4,1,10,14,4,3,0,0,0,2011
0613,0,3,8,40,30,27,6,0,0,0,2011
1406,0,8,18,48,71,36,4,0,0,0,2011
1610,0,0,11,14,16,12,3,0,0,0,2011
1011,0,7,17,40,48,23,6,0,0,0,2011
0503,0,11,30,87,140,73,11,0,0,0,2011
0611,0,3,25,40,61,36,4,1,0,0,2011
1405,0,11,51,88,106,56,8,2,0,0,2011
4203,0,61,110,233,248,109,19,1,0,0,2011
0815,0,1,6,18,21,7,3,0,0,0,2011
0402,0,2,29,64,108,51,7,0,0,0,2011
0114,0,4,15,60,86,40,5,2,0,0,2011
0109,1,28,114,330,513,220,41,1,0,0,2011
0803,0,2,6,7,12,8,1,0,0,0,2011
3106,0,1,5,7,6,3,2,0,0,0,2011
...,...,...,...,...,...,...,...,...,...,...,...
0912,0,8,17,44,56,21,1,0,0,0,2011
0614,0,0,3,9,14,9,2,0,0,0,2011
1703,0,14,32,59,100,36,11,2,0,0,2011
1609,1,19,80,163,264,148,17,0,0,0,2011
0712,0,3,11,23,37,19,2,1,0,0,2011
0406,0,1,5,8,15,4,0,0,0,0,2011
0610,1,6,29,56,111,43,5,1,0,0,2011
0412,0,1,0,16,9,4,1,0,0,0,2011
1414,0,4,19,49,60,30,7,0,0,0,2011
1806,0,7,17,49,55,26,3,0,0,0,2011
1302,0,7,31,45,43,26,4,0,0,0,2011
1812,0,0,1,7,4,2,0,0,0,0,2011
0506,0,1,3,3,7,1,0,0,0,0,2011
1106,2,228,613,1118,2035,1407,312,18,0,0,2011
3107,0,4,16,31,37,32,7,0,0,0,2011
1110,2,38,146,316,660,504,116,8,0,0,2011
1210,0,1,1,4,13,1,0,0,0,0,2011
1003,0,1,2,24,32,15,2,0,0,0,2011
1810,0,2,13,30,33,15,1,0,0,0,2011
1418,0,13,30,62,77,51,12,0,0,0,2011
1506,1,49,119,207,218,147,25,1,0,0,2011
0301,0,3,14,38,57,28,4,0,0,0,2011
3201,0,4,8,9,7,8,2,0,0,0,2011
0907,0,6,24,100,120,66,12,0,0,0,2011
1306,0,36,118,320,513,337,48,4,0,0,2011
1308,0,60,172,379,614,372,65,2,0,0,2011
0213,0,11,19,22,31,15,5,0,0,0,2011
1108,0,10,20,63,93,45,5,0,0,0,2011
0811,0,25,80,195,208,126,24,0,0,0,2011
1013,0,2,5,4,6,1,2,0,0,0,2011